using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FeatureFlags.Data.Interfaces;
using FeatureFlags.Data.Models;

namespace FeatureFlags.Data
{
	//Note - this is autogenerated code
	public interface IDataUnit
	{
		int SaveChanges();
		//void BeginTransaction();
		//void CommitTransaction();
		//void RollbackTransaction();
	
		IGenericRepository<FeatureFlag> FeatureFlagRepository { get;set; }
	
		IGenericRepository<FeatureRole> FeatureRoleRepository { get;set; }
	
		IGenericRepository<FeatureRoleUser> FeatureRoleUserRepository { get;set; }
	
		IGenericRepository<FeatureStateRole> FeatureStateRoleRepository { get;set; }
	
		IGenericRepository<FeatureState> FeatureStateRepository { get;set; }
	}
}


